const express=require('express');
const router=express.Router();
const {poly,polymanytomany,onetomanyinclude,bulk,crudoperation,ope,onetomany,Insertasso,Updateasso,scope,hook,practice,practice2,manytomanyjun,manytomanyjunselect,manytomayinsert}=require('../controller/userController');
router.route('/bulkadd').get(bulk);
router.route('/crud').get(crudoperation);
router.route('/select').get(ope);
router.route('/onetomany').get(onetomany);
router.route('/insertasso').get(Insertasso);
router.route('/updateasso').get(Updateasso);
router.route('/practice').get(practice);
router.route('/practice2').get(practice2);
router.route('/manytomanyjun').get(manytomanyjun);
router.route('/manytomanyjunselect').get(manytomanyjunselect);
router.route('/manytomayinsert').get(manytomayinsert);
router.route('/scope').get(scope);
router.route('/hook').get(hook);
router.route('/poly').get(poly);
router.route('/polymanytomany').get(polymanytomany);
router.route('/onetomanyinclude').get(onetomanyinclude);
module.exports = router;